#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-eo-evnfm-mb.name" . }}-config
  labels: {{- include "eric-eo-evnfm-mb.labels.extended-defaults" . | nindent 4 }}
  {{- include "eric-eo-evnfm-mb.kubernetes-io-info" .| nindent 4 }}
  annotations:
  {{- include "eric-eo-evnfm-mb.annotations" .| nindent 4 }}
data:
  enabled_plugins: |-
{{ template "eric-eo-evnfm-mb.plugins" . }}
  rabbitmq.conf: |-
    ##username and password
    default_user=CHANGEME
    default_pass=CHANGEME
{{- if .Values.global.support.ipv6.enabled }}
    management.tcp.ip = ::
{{- end }}
{{ .Values.rabbitmq.configuration | indent 4 }}
{{ .Values.rabbitmq.extraConfiguration | indent 4 }}
{{ if .Values.rabbitmq.advancedConfiguration}}
  advanced.config: |-
{{ .Values.rabbitmq.advancedConfiguration | indent 4 }}
{{ end }}
  erl_inetrc: |-
    {inet6,true}.
