#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "eric-eo-evnfm-mb.name" . }}
  labels:
{{- if .Values.ingress.ingressClass }}
    kubernetes.io/ingress.class: {{.Values.ingress.ingressClass }}
{{- end -}}
    {{- include "eric-eo-evnfm-mb.labels.extended-defaults" . | nindent 4 }}
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: {{ template "eric-eo-evnfm-mb.chart" .  }}
  annotations:
    {{- include "eric-eo-evnfm-mb.annotations" .| nindent 4 }}
    {{- if .Values.ingress.tls }}
    ingress.kubernetes.io/secure-backends: "true"
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  {{- if .Values.ingress.hostName }}
  - host: {{ .Values.ingress.hostName }}
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
        - path: {{ .Values.ingress.path }}
          backend:
            serviceName: {{ template "eric-eo-evnfm-mb.name" . }}
            servicePort: {{ .Values.service.managerPort }}
{{- if .Values.ingress.tls }}
  tls:
  - hosts:
    {{- if  .Values.ingress.hostName }}
    - {{ .Values.ingress.hostName }}
    secretName: {{  .Values.ingress.tlsSecret }}
    {{- else}}
    - secretName: {{  .Values.ingress.tlsSecret }}
    {{- end }}
{{- end }}
{{- end }}
