#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-eo-evnfm-mb.name" . }}-{{ template "eric-eo-evnfm-mb.privileged.cluster.role.name" . }}-psp-binding
  labels: {{- include "eric-eo-evnfm-mb.labels.extended-defaults" . | nindent 4 }}
  annotations:
  {{- include "eric-eo-evnfm-mb.annotations" .| nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ template "eric-eo-evnfm-mb.privileged.cluster.role.name" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ template "eric-eo-evnfm-mb.name" . }}
