#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{ if not .Values.rabbitmq.existingErlangSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "eric-eo-evnfm-mb.name" . }}
  labels:
    {{- include "eric-eo-evnfm-mb.labels.extended-defaults" .| nindent 4 }}
    app.kubernetes.io/managed-by: Tiller
    helm.sh/chart: {{ template "eric-eo-evnfm-mb.chart" .  }}
  annotations:
  {{ include "eric-eo-evnfm-mb.annotations" . | indent 2 }}
type: Opaque
data:
  {{ if not .Values.rabbitmq.existingErlangSecret }}{{ if .Values.rabbitmq.erlangCookie }}
  rabbitmq-erlang-cookie: {{ .Values.rabbitmq.erlangCookie | b64enc | quote }}
  {{ else }}
  rabbitmq-erlang-cookie: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}{{ end }}
{{ end }}
